### ISSUE TITLE
LXC-CLIENT

### ISSUE THREAD

**Issue by OpenOS-Project-Creator-Founder** [randombenj/lxd-deb#12]
dpkg: error processing archive /var/cache/apt/archives/lxd-client_243a5.14-2_amd64.deb (--unpack): trying to overwrite "/usr/share/bash-completion/completions/lxc', which is also in package lxc-utils 1:4.0.12-0ubuntu1-20.04.1

Errors were encountered while processing:

/var/cache/apt/archives/lxd-client_2%3a5.14-2_amd64.deb E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by randombenj** [comment]
@gianfurrer maybe we should add a conflicts or so to the deb package?
Also `lxd-agent-loader` seems to conflict

**Comment by gianfurrer** [comment]
I will look into it
